# configuration for https://github.com/orhun/git-cliff

[remote.gitea]
owner = "meli"
repo = "meli"

[changelog]
# changelog header
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
# note that the - before / after the % controls whether whitespace is rendered between each line.
# Getting this right so that the markdown renders with the correct number of lines between headings
# code fences and list items is pretty finicky. Note also that the 4 backticks in the commit macro
# is intentional as this escapes any backticks in the commit body.
body = """

{% if not version %}
## Unreleased
{% else %}
## [{{ version }}]({{ "https://git.meli-email.org/meli/meli/releases/tag/" ~ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% endif %}{% if get_env(name = "FRIENDS", default = "") != "" %}
Contributors in alphabetical order:

{{ get_env(name = "FRIENDS") }}
{%- endif -%}{% if gitea and gitea.contributors %}{% for contributor in gitea.contributors | filter(attribute="is_first_time", value=true) %}
  * [@{{ contributor.username }}](https://git.meli-email.org/{{ contributor.username }}) made their first contribution in [#{{ contributor.pr_number }}]({{ "https://git.meli-email.org/meli/meli/pulls/" ~ contributor.pr_number }})
{%- endfor -%}{%- endif -%}{% macro commit(commit) -%}
- [**`{{ commit.id | truncate(length=8, end="") }}`**]({{ "https://git.meli-email.org/meli/meli/commit/" ~ commit.id }}) {% if commit.scope %}*({{commit.scope | lower }})* {% endif %}`{{ commit.message | split(pat="\n")| first }}`{% if commit.remote and commit.remote.pr_number and commit.remote.pr_title %} in PR [`#{{ commit.remote.pr_number }}` "{{ commit.remote.pr_title }}"]({{ "https://git.meli-email.org/meli/meli/pulls/" ~ commit.remote.pr_number }}){%- endif -%}{% endmacro -%}
{% for group, commits in commits | group_by(attribute="group") %}

### {{ group | striptags | trim | upper_first }}
{% for commit in commits | filter(attribute="scope") | sort(attribute="scope") %}
{{ self::commit(commit=commit) }}
{%- endfor -%}
{% for commit in commits %}
{%- if not commit.scope %}
{{ self::commit(commit=commit) }}
{%- endif -%}
{%- endfor -%}
{%- endfor %}
"""

# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """


<!-- generated by git-cliff <https://git-cliff.org> -->
"""

[git]
# don't parse the commits based on https://www.conventionalcommits.org
conventional_commits = false
# filter out the commits that are not conventional
filter_unconventional = false
# process each line of a commit as an individual commit
split_commits = false
# regex for preprocessing the commit messages
commit_preprocessors = [
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://git.meli-email.org/meli/meli/issues/${2}))" }, # Replace the issue number with the link
  { pattern = " +", replace = " "}, # Replace multiple spaces with a single space
  { pattern = "`[^`]+`", replace_command = "pandoc -f commonmark -t plain" },
]
# regex for parsing and grouping commits
commit_parsers = [
  { message = "^chore\\(changelog\\)", skip = true },
  { message = "^chore\\(deps\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^CHANGELOG", skip = true },
  { message = "(?i)^revert", group = "<!-- 11 -->Reverted Commits" },
  { message = "^.github", group = "<!-- 10 -->Continuous Integration" },
  { message = "^.gitea", group = "<!-- 10 -->Continuous Integration" },
  { message = "(?i)^ci", group = "<!-- 10 -->Continuous Integration" },
  { message = "^build", group = "<!-- 09 -->Build" },
  { body = ".*security", group = "<!-- 08 -->Security" },
  { message = "^scripts", group = "<!-- 07 -->Miscellaneous Tasks" },
  { message = '(?i)^chore', group = "<!-- 07 -->Miscellaneous Tasks" },
  { message = "^debian", group = "<!-- 06 -->Packaging" },
  { message = "^test", group = "<!-- 06 -->Testing" },
  { message = "^style", group = "<!-- 05 -->Styling" },
  { message = "^perf", group = "<!-- 04 -->Performance" },
  { message = "(?i)readme", group = "<!-- 03 -->Documentation" },
  { message = "(?i)anpage", group = "<!-- 03 -->Documentation" },
  { message = "(?i)anual", group = "<!-- 03 -->Documentation" },
  { message = "meli.[17]", group = "<!-- 03 -->Documentation" },
  { message = "meli.conf.5", group = "<!-- 03 -->Documentation" },
  { message = "meli-themes.5", group = "<!-- 03 -->Documentation" },
  { message = "README.md", group = "<!-- 03 -->Documentation" },
  { message = "BUILD.md", group = "<!-- 03 -->Documentation" },
  { message = "DEVELOPMENT.md", group = "<!-- 03 -->Documentation" },
  { message = "^doc", group = "<!-- 03 -->Documentation" },
  { message = "^[^.]*.rs:", group = "<!-- 02 -->Refactoring" },
  { message = '(?i)^refactor\b', group = "<!-- 02 -->Refactoring" },
  { message = '(?i)lints?\b', group = "<!-- 02 -->Refactoring" },
  { message = '(?i)move\b', group = "<!-- 02 -->Refactoring" },
  { message = '(?i)replace\b', group = "<!-- 02 -->Refactoring" },
  { message = '(?i)remove\b', group = "<!-- 02 -->Refactoring" },
  { message = '(?i)refactor\b', group = "<!-- 02 -->Refactoring" },
  { message = '(?i)rename\b', group = "<!-- 02 -->Refactoring" },
  { message = '(?i)formatting\b', group = "<!-- 02 -->Refactoring" },
  { message = '(?i)cleanups?\b', group = "<!-- 02 -->Refactoring" },
  { message = '(?i)fix\b', group = "<!-- 01 -->Bug Fixes" },
  { message = '(?i)fixups?\b', group = "<!-- 01 -->Bug Fixes" },
  { message = "(?i)implement", group = "<!-- 00 -->Added" },
  { message = '(?i)add\b', group = "<!-- 00 -->Added" },
  { message = '(?i)^update\b', group = "<!-- 02 -->Changes" },
  { message = '(?i)\bdependency\b', group = "<!-- 02 -->Changes" },
  { message = "^feat", group = "<!-- 00 -->Added" },
  { message = '(?i)retry\b', group = "<!-- 02 -->Changes" },
  { message = "^conf", group = "<!-- 02 -->Changes" },
  { message = "^contacts?", group = "<!-- 02 -->Changes" },
  { message = "^compos[ie]?", group = "<!-- 02 -->Changes" },
  { message = "^types", group = "<!-- 02 -->Changes" },
  { message = '(?i)^use', group = "<!-- 02 -->Changes" },
  { message = "^terminal", group = "<!-- 02 -->Changes" },
  { message = "^listing", group = "<!-- 02 -->Changes" },
  { message = "^mail", group = "<!-- 02 -->Changes" },
  { message = "^utilities", group = "<!-- 02 -->Changes" },
  { message = "^view", group = "<!-- 02 -->Changes" },
  { message = "^mail/view", group = "<!-- 02 -->Changes" },
  { message = "^backends?", group = "<!-- 02 -->Changes" },
  { message = "^commands?", group = "<!-- 02 -->Changes" },
  { message = "^actions?", group = "<!-- 02 -->Changes" },
  { message = "^log", group = "<!-- 02 -->Changes" },
  { message = "^pgp", group = "<!-- 02 -->Changes" },
  { message = "^gpgme", group = "<!-- 02 -->Changes" },
  { message = "^manage", group = "<!-- 02 -->Changes" },
  { message = "^smtp", group = "<!-- 02 -->Changes" },
  { message = "^mbox", group = "<!-- 02 -->Changes" },
  { message = "^jmap", group = "<!-- 02 -->Changes" },
  { message = "^imap", group = "<!-- 02 -->Changes" },
  { message = "^nntp", group = "<!-- 02 -->Changes" },
  { message = "^notmuch", group = "<!-- 02 -->Changes" },
  { message = "^melib", group = "<!-- 02 -->Changes" },
  { message = "^meli", group = "<!-- 02 -->Changes" },
  { message = "^accounts", group = "<!-- 02 -->Changes" },
  { message = "^embedded", group = "<!-- 02 -->Changes" },
  { message = "^jobs", group = "<!-- 02 -->Changes" },
  { message = ".*", group = "<!-- 07 -->Miscellaneous Tasks" },
]
# protect breaking changes from being skipped due to matching a skipping commit_parser
protect_breaking_commits = false
# filter out the commits that are not matched by commit parsers
filter_commits = false
# glob pattern for matching git tags
tag_pattern = "v[0-9]+|alpha-[0-9]+"
# regex for ignoring tags
ignore_tags = "v[^-]+-rc[.]?[0-9]+"
# regex for skipping tags
#skip_tags = "alpha"
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
